version: '3.1'
services:
  wordpress:
    depends_on:
      - db
    image: wordpress:5.3.2
    restart: always
    volumes:
      - dev-wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: p4ssw0rd!
    ports:
      - 8080:80
    networks:
      - back
  db:
    image: mysql:5.7.29
    restart: always
    volumes:
       - dev-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks:
      - back
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks:
      - back
networks:
  back:
volumes:
  dev-db-data:
  dev-wp-content:
